table channel_efficiency

	column channel
		dataType: string
		summarizeBy: none
		sourceColumn: channel

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column impressions
		dataType: double
		summarizeBy: sum
		sourceColumn: impressions

	column clicks
		dataType: double
		summarizeBy: sum
		sourceColumn: clicks

	column tv_grp
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_grp

	column media_type
		dataType: string
		summarizeBy: none
		sourceColumn: media_type

	column channel_role
		dataType: string
		summarizeBy: none
		sourceColumn: channel_role

	column revenue_attributed
		dataType: boolean
		summarizeBy: sum
		sourceColumn: revenue_attributed

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	column roi_gross_margin
		dataType: double
		summarizeBy: sum
		sourceColumn: roi_gross_margin

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column cpm_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpm_aed

	column cpc_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpc_aed

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column cost_per_grp_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cost_per_grp_aed

	column share_of_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_spend

	column share_of_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_sales

	column efficiency_index
		dataType: double
		summarizeBy: sum
		sourceColumn: efficiency_index

	column payback
		dataType: string
		summarizeBy: none
		sourceColumn: payback

	partition channel_efficiency = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "channel_efficiency.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"channel", type text}, {"spend_aed", type number}, {"sales_aed", type number}, {"conversions", type number}, {"impressions", type number}, {"clicks", type number}, {"tv_grp", type number}, {"media_type", type text}, {"channel_role", type text}, {"revenue_attributed", type logical}, {"roas", type number}, {"roi_gross_margin", type number}, {"cpa_aed", type number}, {"cpm_aed", type number}, {"cpc_aed", type number}, {"aov_aed", type number}, {"cost_per_grp_aed", type number}, {"share_of_spend", type number}, {"share_of_sales", type number}, {"efficiency_index", type number}, {"payback", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
