table dim_product

	column product
		dataType: string
		summarizeBy: none
		sourceColumn: product

	column family
		dataType: string
		summarizeBy: none
		sourceColumn: family

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_product.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"product", type text}, {"family", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
