table dim_influencer

	column influencer
		dataType: string
		summarizeBy: none
		sourceColumn: influencer

	column market
		dataType: string
		summarizeBy: none
		sourceColumn: market

	column followers_median
		dataType: double
		summarizeBy: sum
		sourceColumn: followers_median

	column followers_min
		dataType: double
		summarizeBy: sum
		sourceColumn: followers_min

	column followers_max
		dataType: double
		summarizeBy: sum
		sourceColumn: followers_max

	column followers_unstable
		dataType: boolean
		summarizeBy: sum
		sourceColumn: followers_unstable

	partition dim_influencer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_influencer.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"influencer", type text}, {"market", type text}, {"followers_median", type number}, {"followers_min", type number}, {"followers_max", type number}, {"followers_unstable", type logical}})
				in
				    Typed

	annotation PBI_ResultType = Table
