table fact_market_week

	column week
		dataType: int64
		summarizeBy: none
		sourceColumn: week

	column market
		dataType: string
		summarizeBy: none
		sourceColumn: market

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column impressions
		dataType: double
		summarizeBy: sum
		sourceColumn: impressions

	column clicks
		dataType: double
		summarizeBy: sum
		sourceColumn: clicks

	column paid_spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: paid_spend_aed

	column paid_sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: paid_sales_aed

	column paid_conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: paid_conversions

	column earned_sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: earned_sales_aed

	column earned_conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: earned_conversions

	column tv_spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_spend_aed

	column tv_grp
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_grp

	column sessions
		dataType: double
		summarizeBy: sum
		sourceColumn: sessions

	column website_sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: website_sales_aed

	column pr_mentions
		dataType: double
		summarizeBy: sum
		sourceColumn: pr_mentions

	column share_of_voice
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_voice

	column influencer_spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: influencer_spend_aed

	column website_conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: website_conversions

	column brand_awareness
		dataType: double
		summarizeBy: sum
		sourceColumn: brand_awareness

	column brand_awareness_sd
		dataType: double
		summarizeBy: sum
		sourceColumn: brand_awareness_sd

	column purchase_intent
		dataType: double
		summarizeBy: sum
		sourceColumn: purchase_intent

	column purchase_intent_sd
		dataType: double
		summarizeBy: sum
		sourceColumn: purchase_intent_sd

	column competitor_sov
		dataType: double
		summarizeBy: sum
		sourceColumn: competitor_sov

	column sentiment
		dataType: double
		summarizeBy: sum
		sourceColumn: sentiment

	column sentiment_sd
		dataType: double
		summarizeBy: sum
		sourceColumn: sentiment_sd

	column n_observations
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_observations

	column is_indicative
		dataType: boolean
		summarizeBy: sum
		sourceColumn: is_indicative

	column intent_to_awareness
		dataType: double
		summarizeBy: sum
		sourceColumn: intent_to_awareness

	column mer
		dataType: double
		summarizeBy: sum
		sourceColumn: mer

	column paid_roas
		dataType: double
		summarizeBy: sum
		sourceColumn: paid_roas

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column cpm_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpm_aed

	column cpc_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpc_aed

	column earned_sales_share
		dataType: double
		summarizeBy: sum
		sourceColumn: earned_sales_share

	column tv_spend_share
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_spend_share

	column cost_per_grp_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cost_per_grp_aed

	column sov_gap
		dataType: double
		summarizeBy: sum
		sourceColumn: sov_gap

	column web_conversion_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: web_conversion_rate

	column sales_aed_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed_wow

	column spend_aed_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed_wow

	column conversions_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions_wow

	column brand_awareness_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: brand_awareness_wow

	column purchase_intent_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: purchase_intent_wow

	column sentiment_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: sentiment_wow

	column share_of_voice_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_voice_wow

	column mer_wow
		dataType: double
		summarizeBy: sum
		sourceColumn: mer_wow

	measure 'Sales' = SUM(fact_market_week[sales_aed])
		formatString: "#,0,, \m \A\E\D"

	measure 'Media Spend' = SUM(fact_market_week[spend_aed])
		formatString: "#,0,, \m \A\E\D"

	measure 'Conversions' = SUM(fact_market_week[conversions])
		formatString: "#,0"

	measure 'Impressions' = SUM(fact_market_week[impressions])
		formatString: "#,0"

	measure 'Clicks' = SUM(fact_market_week[clicks])
		formatString: "#,0"

	measure 'Sessions' = SUM(fact_market_week[sessions])
		formatString: "#,0"

	measure 'Paid Spend' = SUM(fact_market_week[paid_spend_aed])
		formatString: "#,0,, \m \A\E\D"

	measure 'Earned Sales' = SUM(fact_market_week[earned_sales_aed])
		formatString: "#,0,, \m \A\E\D"

	measure 'TV Spend' = SUM(fact_market_week[tv_spend_aed])
		formatString: "#,0,, \m \A\E\D"

	measure 'TV GRPs' = SUM(fact_market_week[tv_grp])
		formatString: "#,0"

	measure 'MER' = DIVIDE([Sales], [Media Spend])
		formatString: "#,0.0\x"

	measure 'CPA' = DIVIDE([Media Spend], [Conversions])
		formatString: "#,0 \A\E\D"

	measure 'AOV' = DIVIDE([Sales], [Conversions])
		formatString: "#,0 \A\E\D"

	measure 'CPM' = DIVIDE([Media Spend], [Impressions]) * 1000
		formatString: "#,0.00 \A\E\D"

	measure 'CPC' = DIVIDE([Media Spend], [Clicks])
		formatString: "#,0.00 \A\E\D"

	measure 'CTR' = DIVIDE([Clicks], [Impressions])
		formatString: "0.00%"

	measure 'Cost per GRP' = DIVIDE([TV Spend], [TV GRPs])
		formatString: "#,0 \A\E\D"

	measure 'Earned Share of Sales' = DIVIDE([Earned Sales], [Sales])
		formatString: "0.0%"

	measure 'TV Share of Spend' = DIVIDE([TV Spend], [Media Spend])
		formatString: "0.0%"

	measure 'Spend as % of Sales' = DIVIDE([Media Spend], [Sales])
		formatString: "0.0%"

	measure 'Gross Margin Rate' = 0.22
		formatString: "0%"

	measure 'ROI on Margin' = [MER] * [Gross Margin Rate]
		formatString: "#,0.00\x"

	measure 'Brand Awareness' = AVERAGE(fact_market_week[brand_awareness])
		formatString: "#,0.0"

	measure 'Purchase Intent' = AVERAGE(fact_market_week[purchase_intent])
		formatString: "#,0.0"

	measure 'Sentiment' = AVERAGE(fact_market_week[sentiment])
		formatString: "#,0.00"

	measure 'Share of Voice' = AVERAGE(fact_market_week[share_of_voice])
		formatString: "#,0.0"

	measure 'Competitor SOV' = AVERAGE(fact_market_week[competitor_sov])
		formatString: "#,0.0"

	measure 'SOV Gap' = [Share of Voice] - [Competitor SOV]
		formatString: "+#,0.0;-#,0.0;0.0"

	measure 'Sales PW' =
			VAR w = SELECTEDVALUE(dim_week[week])
			RETURN CALCULATE([Sales], ALL(dim_week), dim_week[week] = w - 1)
		formatString: "#,0,, \m \A\E\D"

	measure 'Sales WoW %' =
			VAR prev = [Sales PW]
			RETURN DIVIDE([Sales] - prev, prev)
		formatString: "+0.0%;-0.0%;0.0%"

	measure 'Spend PW' =
			VAR w = SELECTEDVALUE(dim_week[week])
			RETURN CALCULATE([Media Spend], ALL(dim_week), dim_week[week] = w - 1)
		formatString: "#,0,, \m \A\E\D"

	measure 'Spend WoW %' =
			VAR prev = [Spend PW]
			RETURN DIVIDE([Media Spend] - prev, prev)
		formatString: "+0.0%;-0.0%;0.0%"

	measure 'Peer Median MER' = MEDIANX(ALL(dim_market), CALCULATE([MER]))
		formatString: "#,0.0\x"

	measure 'MER vs Peer Median' = DIVIDE([MER] - [Peer Median MER], [Peer Median MER])
		formatString: "+0.0%;-0.0%;0.0%"

	measure 'Influencer Fees' = SUM(influencer_scorecard[spend_aed])
		formatString: "#,0 \A\E\D"

	measure 'Influencer Conversions' = SUM(influencer_scorecard[conversions])
		formatString: "#,0"

	measure 'Influencer CPA' = DIVIDE([Influencer Fees], [Influencer Conversions])
		formatString: "#,0 \A\E\D"

	measure 'Influencer ROI on Margin' = DIVIDE(SUM(influencer_scorecard[sales_aed]), [Influencer Fees]) * [Gross Margin Rate]
		formatString: "#,0.00\x"

	measure 'Open Alerts' = COUNTROWS(alerts)
		formatString: "#,0"

	measure 'Critical Alerts' = CALCULATE(COUNTROWS(alerts), alerts[severity] = "critical")
		formatString: "#,0"

	partition fact_market_week = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "fact_market_week.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"week", Int64.Type}, {"market", type text}, {"spend_aed", type number}, {"sales_aed", type number}, {"conversions", type number}, {"impressions", type number}, {"clicks", type number}, {"paid_spend_aed", type number}, {"paid_sales_aed", type number}, {"paid_conversions", type number}, {"earned_sales_aed", type number}, {"earned_conversions", type number}, {"tv_spend_aed", type number}, {"tv_grp", type number}, {"sessions", type number}, {"website_sales_aed", type number}, {"pr_mentions", type number}, {"share_of_voice", type number}, {"influencer_spend_aed", type number}, {"website_conversions", type number}, {"brand_awareness", type number}, {"brand_awareness_sd", type number}, {"purchase_intent", type number}, {"purchase_intent_sd", type number}, {"competitor_sov", type number}, {"sentiment", type number}, {"sentiment_sd", type number}, {"n_observations", Int64.Type}, {"is_indicative", type logical}, {"intent_to_awareness", type number}, {"mer", type number}, {"paid_roas", type number}, {"cpa_aed", type number}, {"aov_aed", type number}, {"cpm_aed", type number}, {"cpc_aed", type number}, {"earned_sales_share", type number}, {"tv_spend_share", type number}, {"cost_per_grp_aed", type number}, {"sov_gap", type number}, {"web_conversion_rate", type number}, {"sales_aed_wow", type number}, {"spend_aed_wow", type number}, {"conversions_wow", type number}, {"brand_awareness_wow", type number}, {"purchase_intent_wow", type number}, {"sentiment_wow", type number}, {"share_of_voice_wow", type number}, {"mer_wow", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
