table fact_channel

	column week
		dataType: int64
		summarizeBy: none
		sourceColumn: week

	column market
		dataType: string
		summarizeBy: none
		sourceColumn: market

	column channel
		dataType: string
		summarizeBy: none
		sourceColumn: channel

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column impressions
		dataType: double
		summarizeBy: sum
		sourceColumn: impressions

	column clicks
		dataType: double
		summarizeBy: sum
		sourceColumn: clicks

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column tv_grp
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_grp

	column engagement_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: engagement_rate

	column sessions
		dataType: double
		summarizeBy: sum
		sourceColumn: sessions

	column pr_mentions
		dataType: double
		summarizeBy: sum
		sourceColumn: pr_mentions

	column pr_share_of_voice
		dataType: double
		summarizeBy: sum
		sourceColumn: pr_share_of_voice

	column products_active
		dataType: int64
		summarizeBy: sum
		sourceColumn: products_active

	column media_type
		dataType: string
		summarizeBy: none
		sourceColumn: media_type

	column channel_role
		dataType: string
		summarizeBy: none
		sourceColumn: channel_role

	column revenue_attributed
		dataType: boolean
		summarizeBy: sum
		sourceColumn: revenue_attributed

	column cpm_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpm_aed

	column cpc_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpc_aed

	column ctr
		dataType: double
		summarizeBy: sum
		sourceColumn: ctr

	column cvr
		dataType: double
		summarizeBy: sum
		sourceColumn: cvr

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column cost_per_grp_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cost_per_grp_aed

	partition fact_channel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "fact_channel.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"week", Int64.Type}, {"market", type text}, {"channel", type text}, {"spend_aed", type number}, {"impressions", type number}, {"clicks", type number}, {"conversions", type number}, {"sales_aed", type number}, {"tv_grp", type number}, {"engagement_rate", type number}, {"sessions", type number}, {"pr_mentions", type number}, {"pr_share_of_voice", type number}, {"products_active", Int64.Type}, {"media_type", type text}, {"channel_role", type text}, {"revenue_attributed", type logical}, {"cpm_aed", type number}, {"cpc_aed", type number}, {"ctr", type number}, {"cvr", type number}, {"cpa_aed", type number}, {"roas", type number}, {"aov_aed", type number}, {"cost_per_grp_aed", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
