table fact_influencer

	column week
		dataType: int64
		summarizeBy: none
		sourceColumn: week

	column market
		dataType: string
		summarizeBy: none
		sourceColumn: market

	column product
		dataType: string
		summarizeBy: none
		sourceColumn: product

	column influencer
		dataType: string
		summarizeBy: none
		sourceColumn: influencer

	column followers
		dataType: double
		summarizeBy: sum
		sourceColumn: followers

	column engagement_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: engagement_rate

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	partition fact_influencer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "fact_influencer.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"week", Int64.Type}, {"market", type text}, {"product", type text}, {"influencer", type text}, {"followers", type number}, {"engagement_rate", type number}, {"spend_aed", type number}, {"conversions", type number}, {"sales_aed", type number}, {"cpa_aed", type number}, {"roas", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
