table influencer_scorecard

	column influencer
		dataType: string
		summarizeBy: none
		sourceColumn: influencer

	column market
		dataType: string
		summarizeBy: none
		sourceColumn: market

	column followers
		dataType: double
		summarizeBy: sum
		sourceColumn: followers

	column engagement_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: engagement_rate

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column weeks_active
		dataType: int64
		summarizeBy: sum
		sourceColumn: weeks_active

	column products
		dataType: int64
		summarizeBy: sum
		sourceColumn: products

	column followers_unstable
		dataType: boolean
		summarizeBy: sum
		sourceColumn: followers_unstable

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	column roi_gross_margin
		dataType: double
		summarizeBy: sum
		sourceColumn: roi_gross_margin

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column cost_per_follower
		dataType: double
		summarizeBy: sum
		sourceColumn: cost_per_follower

	column er_vs_roster
		dataType: double
		summarizeBy: sum
		sourceColumn: er_vs_roster

	column cpa_vs_roster
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_vs_roster

	column flag
		dataType: string
		summarizeBy: none
		sourceColumn: flag

	column recommended_action
		dataType: string
		summarizeBy: none
		sourceColumn: recommended_action

	column spend_at_median_cpa
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_at_median_cpa

	column excess_spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: excess_spend_aed

	partition influencer_scorecard = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "influencer_scorecard.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"influencer", type text}, {"market", type text}, {"followers", type number}, {"engagement_rate", type number}, {"spend_aed", type number}, {"conversions", type number}, {"sales_aed", type number}, {"weeks_active", Int64.Type}, {"products", Int64.Type}, {"followers_unstable", type logical}, {"cpa_aed", type number}, {"roas", type number}, {"roi_gross_margin", type number}, {"aov_aed", type number}, {"cost_per_follower", type number}, {"er_vs_roster", type number}, {"cpa_vs_roster", type number}, {"flag", type text}, {"recommended_action", type text}, {"spend_at_median_cpa", type number}, {"excess_spend_aed", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
