table market_scorecard

	column market
		dataType: string
		summarizeBy: none
		sourceColumn: market

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column paid_spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: paid_spend_aed

	column earned_sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: earned_sales_aed

	column tv_spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_spend_aed

	column brand_awareness
		dataType: double
		summarizeBy: sum
		sourceColumn: brand_awareness

	column purchase_intent
		dataType: double
		summarizeBy: sum
		sourceColumn: purchase_intent

	column share_of_voice
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_voice

	column competitor_sov
		dataType: double
		summarizeBy: sum
		sourceColumn: competitor_sov

	column sentiment
		dataType: double
		summarizeBy: sum
		sourceColumn: sentiment

	column sessions
		dataType: double
		summarizeBy: sum
		sourceColumn: sessions

	column mer
		dataType: double
		summarizeBy: sum
		sourceColumn: mer

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column earned_sales_share
		dataType: double
		summarizeBy: sum
		sourceColumn: earned_sales_share

	column tv_spend_share
		dataType: double
		summarizeBy: sum
		sourceColumn: tv_spend_share

	column sov_gap
		dataType: double
		summarizeBy: sum
		sourceColumn: sov_gap

	column spend_share_of_group
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_share_of_group

	column sales_share_of_group
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_share_of_group

	column mer_vs_peer_median
		dataType: double
		summarizeBy: sum
		sourceColumn: mer_vs_peer_median

	column sales_at_peer_median_mer
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_at_peer_median_mer

	column sales_gap_vs_peer_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_gap_vs_peer_aed

	column mer_rank
		dataType: int64
		summarizeBy: sum
		sourceColumn: mer_rank

	column quartile
		dataType: string
		summarizeBy: none
		sourceColumn: quartile

	partition market_scorecard = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "market_scorecard.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"market", type text}, {"spend_aed", type number}, {"sales_aed", type number}, {"conversions", type number}, {"paid_spend_aed", type number}, {"earned_sales_aed", type number}, {"tv_spend_aed", type number}, {"brand_awareness", type number}, {"purchase_intent", type number}, {"share_of_voice", type number}, {"competitor_sov", type number}, {"sentiment", type number}, {"sessions", type number}, {"mer", type number}, {"cpa_aed", type number}, {"aov_aed", type number}, {"earned_sales_share", type number}, {"tv_spend_share", type number}, {"sov_gap", type number}, {"spend_share_of_group", type number}, {"sales_share_of_group", type number}, {"mer_vs_peer_median", type number}, {"sales_at_peer_median_mer", type number}, {"sales_gap_vs_peer_aed", type number}, {"mer_rank", Int64.Type}, {"quartile", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
