table paid_vs_earned

	column media_type
		dataType: string
		summarizeBy: none
		sourceColumn: media_type

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column share_of_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_spend

	column share_of_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_sales

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	partition paid_vs_earned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "paid_vs_earned.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"media_type", type text}, {"spend_aed", type number}, {"sales_aed", type number}, {"conversions", type number}, {"share_of_spend", type number}, {"share_of_sales", type number}, {"aov_aed", type number}, {"roas", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
