table panel_model

	column channel
		dataType: string
		summarizeBy: none
		sourceColumn: channel

	column coefficient
		dataType: double
		summarizeBy: sum
		sourceColumn: coefficient

	column std_error
		dataType: double
		summarizeBy: sum
		sourceColumn: std_error

	column p_value
		dataType: double
		summarizeBy: sum
		sourceColumn: p_value

	column ci_low
		dataType: double
		summarizeBy: sum
		sourceColumn: ci_low

	column ci_high
		dataType: double
		summarizeBy: sum
		sourceColumn: ci_high

	column significant_5pct
		dataType: boolean
		summarizeBy: sum
		sourceColumn: significant_5pct

	column interpretation
		dataType: string
		summarizeBy: none
		sourceColumn: interpretation

	column r_squared
		dataType: double
		summarizeBy: sum
		sourceColumn: r_squared

	column n_observations
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_observations

	column model_note
		dataType: string
		summarizeBy: none
		sourceColumn: model_note

	partition panel_model = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "panel_model.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"channel", type text}, {"coefficient", type number}, {"std_error", type number}, {"p_value", type number}, {"ci_low", type number}, {"ci_high", type number}, {"significant_5pct", type logical}, {"interpretation", type text}, {"r_squared", type number}, {"n_observations", Int64.Type}, {"model_note", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
