table product_summary

	column product
		dataType: string
		summarizeBy: none
		sourceColumn: product

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	column aov_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: aov_aed

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column share_of_spend
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_spend

	column share_of_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: share_of_sales

	column support_index
		dataType: double
		summarizeBy: sum
		sourceColumn: support_index

	partition product_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "product_summary.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"product", type text}, {"spend_aed", type number}, {"sales_aed", type number}, {"conversions", type number}, {"roas", type number}, {"aov_aed", type number}, {"cpa_aed", type number}, {"share_of_spend", type number}, {"share_of_sales", type number}, {"support_index", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
