table product_channel

	column product
		dataType: string
		summarizeBy: none
		sourceColumn: product

	column channel
		dataType: string
		summarizeBy: none
		sourceColumn: channel

	column spend_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: spend_aed

	column sales_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: sales_aed

	column conversions
		dataType: double
		summarizeBy: sum
		sourceColumn: conversions

	column roas
		dataType: double
		summarizeBy: sum
		sourceColumn: roas

	column cpa_aed
		dataType: double
		summarizeBy: sum
		sourceColumn: cpa_aed

	column roas_index_vs_product
		dataType: double
		summarizeBy: sum
		sourceColumn: roas_index_vs_product

	partition product_channel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "product_channel.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"product", type text}, {"channel", type text}, {"spend_aed", type number}, {"sales_aed", type number}, {"conversions", type number}, {"roas", type number}, {"cpa_aed", type number}, {"roas_index_vs_product", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
